"""empty message

Revision ID: b74ad89616bc
Revises: 
Create Date: 2019-06-28 12:18:08.868089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74ad89616bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('semester',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('season', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semester_department'), 'semester', ['department'], unique=False)
    op.create_index(op.f('ix_semester_season'), 'semester', ['season'], unique=False)
    op.create_index(op.f('ix_semester_year'), 'semester', ['year'], unique=False)
    op.create_table('user_model',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('firstname', sa.String(length=64), nullable=True),
    sa.Column('lastname', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('class_jurisdiction', sa.String(length=256), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('authentication_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_model_department'), 'user_model', ['department'], unique=False)
    op.create_index(op.f('ix_user_model_email'), 'user_model', ['email'], unique=True)
    op.create_index(op.f('ix_user_model_firstname'), 'user_model', ['firstname'], unique=False)
    op.create_index(op.f('ix_user_model_lastname'), 'user_model', ['lastname'], unique=False)
    op.create_table('class',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('class_number', sa.String(length=64), nullable=True),
    sa.Column('class_section', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('professor', sa.String(length=64), nullable=True),
    sa.Column('class_location', sa.String(length=64), nullable=True),
    sa.Column('percentage_filled', sa.Float(), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('num_enrolled_students', sa.Integer(), nullable=True),
    sa.Column('potentially_enrolled_students', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('days', sa.String(length=5), nullable=True),
    sa.Column('class_time', sa.String(length=64), nullable=True),
    sa.Column('semester_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semester.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_class_location'), 'class', ['class_location'], unique=False)
    op.create_index(op.f('ix_class_class_number'), 'class', ['class_number'], unique=False)
    op.create_index(op.f('ix_class_class_section'), 'class', ['class_section'], unique=False)
    op.create_index(op.f('ix_class_class_time'), 'class', ['class_time'], unique=False)
    op.create_index(op.f('ix_class_days'), 'class', ['days'], unique=False)
    op.create_index(op.f('ix_class_department'), 'class', ['department'], unique=False)
    op.create_index(op.f('ix_class_max_capacity'), 'class', ['max_capacity'], unique=False)
    op.create_index(op.f('ix_class_num_enrolled_students'), 'class', ['num_enrolled_students'], unique=False)
    op.create_index(op.f('ix_class_percentage_filled'), 'class', ['percentage_filled'], unique=False)
    op.create_index(op.f('ix_class_potentially_enrolled_students'), 'class', ['potentially_enrolled_students'], unique=False)
    op.create_index(op.f('ix_class_professor'), 'class', ['professor'], unique=False)
    op.create_index(op.f('ix_class_season'), 'class', ['season'], unique=False)
    op.create_index(op.f('ix_class_subject'), 'class', ['subject'], unique=False)
    op.create_index(op.f('ix_class_year'), 'class', ['year'], unique=False)
    op.create_table('override',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('student_name', sa.String(length=64), nullable=True),
    sa.Column('student_A_number', sa.String(length=64), nullable=True),
    sa.Column('registration_status', sa.Boolean(), nullable=False),
    sa.Column('creator', sa.String(length=10), nullable=True),
    sa.Column('student_netid', sa.String(length=10), nullable=True),
    sa.Column('date_created', sa.String(length=10), nullable=True),
    sa.Column('class_id', sa.String(length=64), nullable=True),
    sa.Column('season', sa.String(length=10), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('days_active', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_override_creator'), 'override', ['creator'], unique=False)
    op.create_index(op.f('ix_override_date_created'), 'override', ['date_created'], unique=False)
    op.create_index(op.f('ix_override_days_active'), 'override', ['days_active'], unique=False)
    op.create_index(op.f('ix_override_department'), 'override', ['department'], unique=False)
    op.create_index(op.f('ix_override_id'), 'override', ['id'], unique=False)
    op.create_index(op.f('ix_override_season'), 'override', ['season'], unique=False)
    op.create_index(op.f('ix_override_student_A_number'), 'override', ['student_A_number'], unique=False)
    op.create_index(op.f('ix_override_student_name'), 'override', ['student_name'], unique=False)
    op.create_index(op.f('ix_override_student_netid'), 'override', ['student_netid'], unique=False)
    op.create_index(op.f('ix_override_year'), 'override', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_override_year'), table_name='override')
    op.drop_index(op.f('ix_override_student_netid'), table_name='override')
    op.drop_index(op.f('ix_override_student_name'), table_name='override')
    op.drop_index(op.f('ix_override_student_A_number'), table_name='override')
    op.drop_index(op.f('ix_override_season'), table_name='override')
    op.drop_index(op.f('ix_override_id'), table_name='override')
    op.drop_index(op.f('ix_override_department'), table_name='override')
    op.drop_index(op.f('ix_override_days_active'), table_name='override')
    op.drop_index(op.f('ix_override_date_created'), table_name='override')
    op.drop_index(op.f('ix_override_creator'), table_name='override')
    op.drop_table('override')
    op.drop_index(op.f('ix_class_year'), table_name='class')
    op.drop_index(op.f('ix_class_subject'), table_name='class')
    op.drop_index(op.f('ix_class_season'), table_name='class')
    op.drop_index(op.f('ix_class_professor'), table_name='class')
    op.drop_index(op.f('ix_class_potentially_enrolled_students'), table_name='class')
    op.drop_index(op.f('ix_class_percentage_filled'), table_name='class')
    op.drop_index(op.f('ix_class_num_enrolled_students'), table_name='class')
    op.drop_index(op.f('ix_class_max_capacity'), table_name='class')
    op.drop_index(op.f('ix_class_department'), table_name='class')
    op.drop_index(op.f('ix_class_days'), table_name='class')
    op.drop_index(op.f('ix_class_class_time'), table_name='class')
    op.drop_index(op.f('ix_class_class_section'), table_name='class')
    op.drop_index(op.f('ix_class_class_number'), table_name='class')
    op.drop_index(op.f('ix_class_class_location'), table_name='class')
    op.drop_table('class')
    op.drop_index(op.f('ix_user_model_lastname'), table_name='user_model')
    op.drop_index(op.f('ix_user_model_firstname'), table_name='user_model')
    op.drop_index(op.f('ix_user_model_email'), table_name='user_model')
    op.drop_index(op.f('ix_user_model_department'), table_name='user_model')
    op.drop_table('user_model')
    op.drop_index(op.f('ix_semester_year'), table_name='semester')
    op.drop_index(op.f('ix_semester_season'), table_name='semester')
    op.drop_index(op.f('ix_semester_department'), table_name='semester')
    op.drop_table('semester')
    # ### end Alembic commands ###
